# action.yml
name: "sharelatex Sync with Git"
branding:
  icon: 'align-center'  
  color: 'yellow'
description: "🤖 A GitHub action to take backups from sharelatex which is an Online LaTeX Editor."


inputs:
  OVERLEAF_COOKIE: # id of input
    description: "Active Cookie of sharelatex account"
    required: true
  OVERLEAF_PROJECT_ID: # id of input
    description: "Id of the project you want the bot to take automatic snapshot"
    required: true
  OVERLEAF_HOST:
    description: "Hostname of your sharelatex Instance, default is sharelatex.cstcloud.cn"
    default: "sharelatex.cstcloud.cn"


runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.sharelatex_COOKIE }}
    - ${{ inputs.OVERLEAF_PROJECT_ID }}
    - ${{ inputs.OVERLEAF_HOST }}

